### ISSUE TITLE
gitlab: user friendly workflow name for the workflows triggered by GitLab

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#177]
When a workflow is created by the GitLab integration, we use the full GitLab project name to name the workflow, while doing this we [replace the slash between `<gitlab_username>/<gitlab_repo>` with the URL encoded form](https://github.com/reanahub/reana-server/blob/fb1dc2a74276999dd44359dc4f9f7b2d73a19f94/reana_server/rest/workflows.py#L281).
- This is not supported by REANA-Client, so `reana-client status -w diegodelemos%2Freana-demo-helloworld` would fail
- It is not user firendly to have workflows named as `diegodelemos%2Freana-demo-helloworld`.

We should discuss how this naming should look like.

**Comment by diegodelemos** [comment]
CC @tiborsimko

**Comment by tiborsimko** [comment]
We could take just the repository name part, it should represent the analysis name quite well already.  

It should not be necessary to keep the user name if we are always mapping one-on-one....

**Comment by mvidalgarcia** [comment]
There's a reason behind the `%2F` substitution. When updating the commit status we pass the GitLab project full name (i.e. `user/project`) and the `/` char must be encoded, otherwise it fails.
Just taking the repository name part as @tiborsimko mentioned is not a valid solution since then we would lack the user and the commit update would fail.

Another solution that I've tried is saving the workflow name as the full project name and only encode it when calling the GitLab API. This works but it results in a series of side effects like the impossibility of [deleting workflows](https://reana-server.readthedocs.io/en/latest/_static/api.html#operation/set_workflow_status) from reana-client as the workflow name is being used directly in the REST API call as part of the URL and the slash is causing issues.

A cleaner solution IMO would be adding to the [`Workflow`](https://github.com/reanahub/reana-db/blob/master/reana_db/models.py#L79) model two new columns: `git_repo` (e.g. `mvidalga/my-project`) & `git_provider` (e.g. `gitlab`) and save the full project name there together with the git provider (this can be useful for the future in case we want to integrate GitHub as well). Then when doing operations related to a `git_provider` we can make use of the `git_repo` avoiding side-effects caused by the presence of special chars.

What do you think?

**Comment by diegodelemos** [comment]
I like the idea. Just to confirm:
1. Two new columns: `git_repo` and `git_provider`.
   - `git_repo`: solves the problem to [update the status against the GitLab API](https://github.com/reanahub/reana-workflow-controller/blob/88a39fef096e82ea5aef112e9c3629ee54a656a1/reana_workflow_controller/consumer.py#L95-L99) (it needs the fully qualified name) -> immediate use
   - `git_provider`: since we introduce `git_repo`, it makes sense to know in which provider it is hosted -> future extensibility
2. Using the old column [`name`](https://github.com/reanahub/reana-db/blob/b346f335ee01a0ffcbfe66d9473e54b68adde672/reana_db/models.py#L85), holding the repo name without the org/user prefix to not breake our API -> immediate use

For example: `https://gitlab-test.cern.ch/rodrigdi/test-reana`
- `git_repo = rodrigdi/reana-demo-helloworld`
- `git_provider = gitlab-test.cern.ch`
- `name = reana-demo-helloworld`

Right? :)
