### ISSUE TITLE
implementation: pagination

### ISSUE THREAD

**Issue by Sinclert** [reanahub/reana-server#180]
Given that the list of workflows can be really long (100+), pagination over the workflows list is handy. This pagination could be implemented either in the server side, or in the client one.

This issue is to discuss the final implementation.

**Comment by mvidalgarcia** [comment]
I will dump my thoughts on this subject because I think implementing pagination on the server-side is an important decision that can impact **a lot** (for the good or for the bad) the user experience and the overload of the platform.

From the UI point of view and focusing in the workflow list page. When implementing server-side pagination:

**Pros**
- The call will be much faster as fewer workflows are loaded.
- Only what's visible is loaded, saving resources and bandwidth.
- In most cases, the user won't navigate through several pages as the most relevant workflows (latest) would be on the first page. This results in a lighter redux state.
- With the current approach of polling results, this approach would have a significantly smaller impact (although the idea is moving to WebSockets).

**Cons**
- Multiple calls to the server: sorting, filtering, search, navigating to other pages and coming back, etc. Whereas implementing client-side pagination, all results would be loaded once and saved in the redux state making sorting, filtering, etc. much faster.
- Keeping a redux state is less relevant in this case as changing page or applying filters would result in different results, sorted differently. This make aggregating results harder and load duplication can happen.
    Example: 
  - User loads the page for the first time and obtains their first 10 workflows.
  - Workflows are saved in the redux store.
  - User filters workflows by state `failed`.
  - A new call to the server-side is performed, fetching the first 10 workflows of state `failed`. Among these workflows, there might be results that were already loaded previously. Let's say 4 of these failed workflows were already loaded (they're being loaded twice) and we aggregate them with the rest so we end up having 16 workflows in the redux state.
  - User goes to a different page, comes back, and applies again the filter by state `failed`. How do we know if the need to perform a new call or reuse what we have in the redux state? Probably a new call is the safest way so redux state loses its purpose for this matter.

**Conclusion**
I think what the best option is really depends on the potential amount of total results, i.e. total number of workflows. For fewer results client-side pagination might fit better and for large datasets server-side might be more appropriate.

I'm sure there are more pros and cons, please share them here. I would like to know your opinion on this as I believe this is a significant change that can cause big headaches if the _wrong_ path is taken. I would also like to know how other applications are facing this.

**Comment by diegodelemos** [comment]
Regarding the potential amount of workflow runs, I think:
  1. It would be safe to think that it would be **at least** as big as the commit history of the analysis.
  2. It will be a constantly growing number.

Both items set a big difference with the room booking in my opinion.

I like the approach you followed in Indico, UX first, maybe we could find some middle ground solution in which we provide a good UX while being efficient? For example, would it be enough to have kind of a most recent list of results (last 200 for example) and perform all normal operations on that set and only search/act on the full history upon user request? We would need concrete requirements to be accurate on this solution.

In any case, I believe we will need the pagination no matter what for the use cases of a "whole history search", or if physics analysis working group conveners want to search in all current analysis they are responsible of etc...

Regarding how it is done in Invenio, by default in Invenio all [records list results are paginated](https://github.com/inveniosoftware/invenio-records-rest/blob/18c5c204d4fbfa77cd9dee643fe09b2fd95e84af/invenio_records_rest/views.py#L600) using [this decorator](https://github.com/inveniosoftware/invenio-records-rest/blob/18c5c204d4fbfa77cd9dee643fe09b2fd95e84af/invenio_records_rest/views.py#L443). If you hit search in Zenodo you will see `Found 1528819 results.`, in opendata.cern.ch `Found 5039 results.`, CDS `Found 633,781 records in 1.38 seconds` etc..

**Comment by tiborsimko** [comment]
Several comments on this that may influence technical planning:

- We shall need pagination not only for the number of workflow runs, but also for other endpoints, such as the number of files produced by a workflow. The analysis outputs can generate thousands of files when studying systematic variations and whatnot. See one example describing [LHCb analysis experiences](https://indico.cern.ch/event/782504/contributions/3288578/attachments/1783778/2903198/2019-01-23_HSF-Analysis-WG.pdf).

- The `reana-client' CLI client will profit from pagination-like experience too. Listing O(1000) files in the workspace will be slow, so we shall be needing either simple pagination or, even better, combined with filtering. Use case example: "return all PNG files from my workspace whose filename start with 'muon'.". This is similar to the use case "return all my workflow runs that failed".

- Another example of an endpoint that may return a lot of output is workflow steps.  Some workflows can be O(10000) steps, so returning logs would take a lot of time. We are already working on [advanced log filtering](https://github.com/reanahub/reana-client/issues/415#issuecomment-653403828) of the kind `reana-client logs --filter step=gen* --filter status=running`. For now, the implementation is done on the client side, but for O(10000) big workflows, we shall need to do this on the server side. Both for Web UX and CLI UX. No action to take for now, just another good example to have in mind while thinking about pagination.

- Hence it'll be good to design a uniform solution for paginating all our REST API endpoints that may generate many files, using "start" and "number of hits per page" standard techniques, for example similar to what we've been doing in Invenio. See the rationale in the [old RFC pagination discussion](https://github.com/inveniosoftware/invenio/issues/1724) and the later decorator implementation.

- Another (future) use case to ponder is combining outputs from several workflow runs. Example: "compare plots P12 and P42 from workflow runs R34, R38, R39". For this, we'll be needing to filter through many plots that these workflow runs have. This is another use case for server-side pagination combined with filtering, this time not only from the same workflow run, but also across different workflow runs.

- An analysis can be worked upon for many months, so there can be many workflow runs that analyse many input files and produce many plots, each run using many computational steps. This all calls for using server-side pagination and filtering techniques whenever possible; the system will be more robust that way. I fully agree with your redux state con example though; doing new calls may be both simpler and safer. We can start this way and see whether UX would be OK even if not much state is kept in the browser?
