### ISSUE TITLE
api: serve updated parameters in spec endpoint

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-server#226]
The [spec](https://github.com/reanahub/reana-server/blob/master/reana_server/rest/workflows.py#L362) endpoint returns the original REANA specification but doesn't update its parameters when those are set via reana-client.

Steps to reproduce:

1. Run (reana-demo-root6-roofit)
```console
 reana-client run -w roofit -p events=1000
```

2. Go to UI, workflow details page, Specification tab and check `parameters`.

Can be addressed at the same time as https://github.com/reanahub/reana-server/issues/227 if possible.

**Comment by mvidalgarcia** [comment]
As discussed during the standup we decided to keep  `Workflow.reana_specification` as the source of truth and never modify it. Aggregations/overwritings as operational input parameters must be handled per operation basis, as done in the [`diff` operation](https://github.com/reanahub/reana-workflow-controller/pull/307).

Now the problem arises on how to display this information in the UI. Some ideas that come to my head:

- a) Create a new tab for input parameters. (Perhaps overkill and mostly empty).
- b) Display a small box in the specification tab on top of the specification itself with the passed parameters. Return operational params in the same endpoint.
- c) Display specification using `diff` format, so user is aware of original and new value.

@reanahub/developers WDYT? 💭

**Comment by diegodelemos** [comment]
I agree option a) would be an overkill if it only contains `inputs.parameters` , however,  what if it contains all `inputs` (`reana.yaml` speaking it would be `parameters` and `files`)? For instance, the alice lego train has many input files see [here](https://github.com/reanahub/reana-demo-alice-lego-train-test-run/blob/f810dc9f78ca9778e41c0bbbf0bc7cdd97abd223/reana.yaml#L3-L13).

Option b) seems to align with what Travis does, note that the different sections can be expanded and collapsed:
![image](https://user-images.githubusercontent.com/9035606/77047282-c3efca80-69c4-11ea-8034-855b343e96ec.png)

Regarding option c) I think we should leave diff views to the diff feature itself (when one could, for instance, select two workflow runs and perform a `diff` action) otherwise I believe it would be confusing. We could use a visual aid instead, for example, gently highlighting the line and a tooltip to explain the situation (of course better than this 😅):
![Screenshot 2020-03-19 at 10 01 24](https://user-images.githubusercontent.com/9035606/77049788-02878400-69c9-11ea-8bec-d324420e5ccf.jpg)

For me option c) with a different look than diff is the more informative and compact of the three.

P.S. It would be worth moving this discussion to an issue in REANA-UI.

**Comment by mvidalgarcia** [comment]
I agree that your proposal would be the ideal solution. However, at the moment, our `CodeSnippet` is very limited (that's why I created [this issue](https://github.com/reanahub/reana-ui/issues/68) to evaluate more powerful options) and adding a tooltip would be too much work and it would involve super tricky and dangerours string comparisons. So IMO we should go for option b), at least for the moment.
