### ISSUE TITLE
db: not rolled back transactions bring RS down

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#228]
We have experienced problems with invalid transactions which are not rolled back which bring REANA down ([reported on Mattermost](https://mattermost.web.cern.ch/it-dep/pl/sn5jz6p1rtb6bj8e8th9a7y6ww)). 
```console
$ kubectl logs reana-server-xxxx-xxxx
...
    raise value.with_traceback(tb)                                                                                                                                           
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1171, in _execute_context                                                                    
    conn = self._revalidate_connection()                                              
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 457, in _revalidate_connection                                                               
    "Can't reconnect until invalid "                                                                                                                                         
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back                                                 
[SQL: SELECT user_.created AS user__created, user_.updated AS user__updated, user_.id_ AS user__id_, user_.access_token AS user__access_token, user_.email AS user__email, us
er_.full_name AS user__full_name, user_.username AS user__username  
...
```

As a quick solution, we have restarted the service.

The problem with the DB is something that seems to happen after a certain amount of time that the Flask application has been running passed, even if we are now closing all db sessions correctly (REANA and Invenio, fixed in https://github.com/reanahub/reana-server/pull/224).

This is something happening on the Invenio side as well and the way this is workaround there is by configuring `uwsgi` [`max-requests`](https://uwsgi-docs.readthedocs.io/en/latest/Options.html#max-requests) property to restart the Flask apps after a certain amount of requests, cleaning up those transactions (more about Invenio setup in https://github.com/inveniosoftware/helm-invenio/).

**Comment by tiborsimko** [comment]
PR #224 fixed this problem already, the traceback reported on MM was simply because the fixed version was not deployed on PROD at the time... so a new deployment would fix it.  

However, I fully agree that it would be good to streamline the `uwsgi` configuration indeed :+1: 
Thinking back about the large-file upload troubles [we were profiling](https://github.com/reanahub/reana-client/pull/324#issuecomment-542760501) in the past, it would be good to do the same for `uwsgi` configuration updates. E.g. measuring a lot of user requests to `ping` and other endpoints using `locustio` and see how `uwsgi` behaves.
