### ISSUE TITLE
disk-quota-update: fix broken disk-quota-update

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#355]
The disk quota update cron job is currently failing in `reana-dev.cern.ch`. See:

```
$ kubectl logs reana-disk-quota-update-xxxxxx-yyy
[ERROR]: An error occurred when updating users disk quota usage: REANAMissingWorkspaceError('Directory does not exist.')
```

Note: Needed for 0.8.0 deployment at CERN.

**Comment by mvidalgarcia** [comment]
**Problem**

The root cause of this problem is that users that have never run any workflows don't have the workspace created, so when the cronjob tries to guess the workspace size to update the quota accordingly, it fails due to not existing folder (`'Directory does not exist.'`).

To illustrate better, current `reana-dev` has 6 users:
```python
In [0]: User.query.count()
Out[0]: 6
```

However, there're only 3 workspace paths:
```console
$ ls /var/reana/users/ | wc -l
3
```

This is because 3 users never run any workflow:
```ipython
In [1]: [u.workflows.count() for u in User.query]
Out[1]: [1, 7, 47, 0, 0, 0]
```

**Solution**

The easiest and cleanest solution is catching this exception and set workspace size as 0 if it doesn't exist. We already do this in [another case when calling `get_disk_usage`](https://github.com/reanahub/reana-db/blob/01976eb2f5a9072303715d6ac6fce4ad6de3776f/reana_db/utils.py#L256-L262).
