### ISSUE TITLE
fetcher: improve error messages

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana-server#472]
Currently, the following error is shown when launching a workflow using an invalid GitHub URL

<img width="600" alt="screenshot" src="https://user-images.githubusercontent.com/13397702/161072790-3d23e5c6-2647-415b-9382-f7a05bfb5a81.png">

We should improve the error messages shown to the user when something goes wrong while fetching a remote workflow specification. It might also be a good idea to return a generic error [here](https://github.com/reanahub/reana-server/blob/a4c7f1b11bcab52f8a5fd9ba899b51bdfa9978dc/reana_server/rest/launch.py#L196), instead of the error message of the exception.

**Comment by tiborsimko** [comment]
One easy thing we could do is to keep the detailed error and pass its output through a filter that would replace `r"/var/reana/users/.*?/"`  by `.../`. In this way the user IDs won't leak.

Returning a generic error message might also be good, but then the users might not understand what exactly went wrong, and the cluster admins wouldn't be able to help out.  So if we don't expose the exact cause, we would have to store these exceptions somewhere server-side e.g. in `workflowsfetched` directory or in `r-server` logs, so that cluster admins could eventually help out with diagnosing troubles.
