### ISSUE TITLE
rest: investigate how to handle changes to default retention period

### ISSUE THREAD

**Issue by mdonadoni** [reanahub/reana-server#511]
[...]
3. I am wondering what should happen when the retention period is changed: should the old `**/*` rules be updated to the new limit or should they be kept the same?
[...]

_Originally posted by @mdonadoni in https://github.com/reanahub/reana/issues/652#issuecomment-1172474025_

**Comment by VMois** [comment]
It depends on what users are expecting. The easiest (and safest?) way is to leave it. Then, default rules will only be for new workflows. 

But users might also expect their defaults to change for all workflows. In this case, we can have a situation where the retention periods for older workflows will shrink, and they will be scheduled for deletion on the next cron job. For this, we might need to notify users that defaults have been changed. For example, it will not be nice to suddenly inform them that REANA will delete their important data in one day instead of one year.

**Comment by VMois** [comment]
We should probably proceed with an easier way. If the default value changes, workflows with an old default value will not get updated. We will not need to make any additional changes. I have tested, and as expected, if the default value changes, only new workflows will have it.

If users encounter problems with this approach, we can always reconsider it. 

*note:* One potential downside of not updating previous workflows, for example, is if the default rule was "forever". After updating the value, the workspace retention cron job will never clean the previous workflows, so if this is important, the administrator will need to do that manually.
