### ISSUE TITLE
api: server error when fetching disk usage with the summarize flag activated

### ISSUE THREAD

**Issue by BrunoRosendo** [reanahub/reana-server#521]
For example, in the reana client, when using the `du` command with the summarize flag (`-s` or `--summarize`), the server returns a 500 error with the following output:
```
==> ERROR: Disk usage could not be retrieved: 
'NoneType' object has no attribute 'quota_used'
```

Logs for reana-server:

```
File "/code/reana_server/rest/workflows.py", line 2331, in get_workflow_disk_usage
    disk_usage_info = workflow.get_workspace_disk_usage(
  File "/code/modules/reana-db/reana_db/models.py", line 628, in get_workspace_disk_usage
    raw=workflow_resource.quota_used,
AttributeError: 'NoneType' object has no attribute 'quota_used'
```

**Comment by VMois** [comment]
`reana-client du -s` command works fine for me. Could you please provide a cluster and client version (`reana-client ping`)?

**Comment by VMois** [comment]
`get_workspace_disk_usage` in `Workflow` model ([code](https://github.com/reanahub/reana-db/blob/a1bb1e5cbd7ff314f27f2e7bde2defc79cdd0196/reana_db/models.py#L608)) when requested for a summary of disk usage for workflow (`reana-client du -s`), returns quota values stored in DB which are not updated because quotas are disabled. I assume we should return a disk usage summary even if quotas are disabled.

*note:* quotas logic is quite confusing. We already have an issue that describes some other problems - https://github.com/reanahub/reana-db/issues/158.

Because `get_workspace_disk_usage` is only used in one place, I will change disk usage to summary to calculate it directly from the disk instead querying outdated DB.
