### ISSUE TITLE
docs: token procedures

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-server#57]
After the addition of the user tokens, documentation needs to be updated to show how to get a token
and how to use them.

**Comment by tiborsimko** [comment]
The admin account comes first, because it cannot be done over REST API.

FWIW I'm using the following one-liner to set the token:

```console
$ export REANA_ACCESS_TOKEN=$(kubectl logs server-b6494546-5cf6b | grep access_token: | awk '{print $NF;}')
```

It would be nicer to have something more CLI friendly like: (see also manual DB creation https://github.com/reanahub/reana-cluster/issues/104)

```console
$ reana-cluster db create
$ reana-cluster users create -e admin@example.org -r admin
$ eval $(reana-cluster env) # this will also generate proper REANA_ACCESS_TOKEN=... 
```

for managing admins. 

For managing regular users, it would be nice to have a user import/export facility, so that we one could do things like:

```console
dev> reana-cluster users export > myusers.csv
qa> reana-cluster users import < myusers.csv  
```

We can think of an appropriate script name and the hosting repository (`reana-cluster`, `reana-admin`, ...) and ticketise these separately.

**Comment by diegodelemos** [comment]
>It would be nicer to have something more CLI friendly like: (see also manual DB creation >https://github.com/reanahub/reana-cluster/issues/104)
>
>```console
>$ reana-cluster db create
>$ reana-cluster users create -e admin@example.org -r admin
>$ eval $(reana-cluster env) # this will also generate proper REANA_ACCESS_TOKEN=... 
>```

Addressed in https://github.com/reanahub/reana-cluster/pull/108 with `--all` flag.
